[package]
name        = "csvio"
description = "Flix library to read and write Csv files built on top of Apache Commons Csv."
version     = "0.3.0"
flix        = "0.37.0"
license     = "Apache-2.0"
authors     = ["Stephen Tetley <stephen.tetley@gmail.com>"]

[dependencies]
"github:stephentetley/basis-base"                = "0.4.1"
"github:stephentetley/flix-time"                 = "0.3.1"
"github:stephentetley/graded-lib"                = "0.6.1"
"github:stephentetley/interop-base"              = "0.6.0"
"github:stephentetley/interop-commons-io-bom"    = "0.3.0"

[mvn-dependencies]
"commons-io:commons-io"             = "2.11.0"
"org.apache.commons:commons-csv"    = "1.10.0"